using System.Text.Json;
using DialShift.Core;

namespace DialShift.App.Services;

/// <summary>
/// Reads the tiny first-run starter list (<c>starter-stations.json</c>, generated by the data pipeline from the
/// <c>starter: true</c> rows) that seeds a fresh install with a few known-good stations. The full catalog load stays
/// lazy (D60); this is the one synchronous read the app makes at startup, and only when there is no settings file yet.
/// </summary>
/// <remarks>
/// <para>The file is a bare JSON array of <c>{name, stream_url, tag}</c>. A missing, unreadable or malformed file yields
/// an empty list, so first-run never fails because of it — the Stations page simply shows its empty state.</para>
/// </remarks>
public static class StarterStations
{
    public const string FileName = "starter-stations.json";

    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower };

    /// <summary>Loads the starter stations bundled next to the apphost. Never throws: any failure returns an empty list.</summary>
    public static List<Station> Load(string baseDirectory)
    {
        var path = Path.Combine(baseDirectory, FileName);
        try
        {
            if (!File.Exists(path)) return [];
            var items = JsonSerializer.Deserialize<List<StarterStationDto>>(File.ReadAllText(path), JsonOptions);
            if (items is null) return [];
            var stations = new List<Station>(items.Count);
            foreach (var item in items)
            {
                var name = item.Name?.Trim() ?? "";
                var url = item.StreamUrl?.Trim() ?? "";
                if (name.Length == 0 || !SettingsStore.ValidUrl(url)) continue;
                stations.Add(new Station
                {
                    Name = name,
                    Url = url,
                    Tag = string.IsNullOrWhiteSpace(item.Tag) ? "Internet radio" : item.Tag.Trim()
                });
            }
            return stations;
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or JsonException)
        {
            return [];
        }
    }

    private sealed class StarterStationDto
    {
        public string? Name { get; set; }
        public string? StreamUrl { get; set; }
        public string? Tag { get; set; }
    }
}
